name: 功能建议
description: 为本项目创建一份合理可行的建议
labels:
  - enhancement
assignees:
  - KiyanYang

body:
  - type: textarea
    id: problem-description
    validations:
      required: true
    attributes:
      label: 问题
      description: 描述你想要解决的问题或者功能的使用场景。
      placeholder: |
        清晰且简洁地描述你遇到的问题或功能的使用场景。

  - type: textarea
    id: solution-description
    validations:
      required: true
    attributes:
      label: 解决方案
      description: 清晰且简洁地描述你你预期的解决方案。

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案
      description: 清晰且简洁地描述你考虑的替代方案。

  - type: textarea
    id: additional-info
    attributes:
      label: 附加信息
      description: 添加其他你认为有必要的信息。
