name: Feature request
description: Suggest an idea for HashTool.
labels:
  - enhancement
assignees:
  - KiyanYang

body:
  - type: textarea
    id: problem-description
    validations:
      required: true
    attributes:
      label: Problem
      description: Please describe the problem which your feature request related to.
      placeholder: |
        A clear and concise description of what the problem is.

  - type: textarea
    id: solution-description
    validations:
      required: true
    attributes:
      label: Solution
      description: A clear and concise description of what you want to happen.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
